INFO 2024-12-24 05:48:19,993 views 32 140351447678976 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:48:20,019 views 32 140351447678976 Command output - stdout: 
ERROR 2024-12-24 05:48:20,020 views 32 140351447678976 Command error - stderr: "docker ps" accepts no arguments.
See 'docker ps --help'.

Usage:  docker ps [OPTIONS]

List containers
INFO 2024-12-24 05:48:20,020 views 32 140351447678976 Command return code: 1
INFO 2024-12-24 05:48:20,242 views 32 140351447678976 Received request to launch OpenUAV
INFO 2024-12-24 05:48:20,242 views 32 140351447678976 Checking if container already exists...
INFO 2024-12-24 05:48:20,242 views 32 140351447678976 Executing command: docker ps -a --format '{{.Names}}' --filter name=openuav
INFO 2024-12-24 05:48:20,273 views 32 140351447678976 Command output - stdout: 'openuav'
INFO 2024-12-24 05:48:20,273 views 32 140351447678976 Command return code: 0
INFO 2024-12-24 05:48:20,274 views 32 140351447678976 Container exists, starting existing container...
INFO 2024-12-24 05:48:20,274 views 32 140351447678976 Executing command: docker start openuav
INFO 2024-12-24 05:48:20,601 views 32 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:48:20,602 views 32 140351447678976 Command return code: 0
INFO 2024-12-24 05:48:20,602 views 32 140351447678976 Container started successfully
INFO 2024-12-24 05:48:20,602 views 32 140351447678976 Executing command: docker inspect --format='{{.State.Status}} {{.State.Running}}' openuav
INFO 2024-12-24 05:48:20,651 views 32 140351447678976 Command output - stdout: 'running
ERROR 2024-12-24 05:48:20,651 views 32 140351447678976 Command error - stderr: Error: No such object: {{.State.Running}}'
INFO 2024-12-24 05:48:20,651 views 32 140351447678976 Command return code: 1
INFO 2024-12-24 05:48:20,651 views 32 140351447678976 Container state: 'running
INFO 2024-12-24 05:48:20,652 views 32 140351447678976 Executing command: docker logs openuav --tail 10
INFO 2024-12-24 05:48:20,679 views 32 140351447678976 Command output - stdout: INFO  [px4] Startup script returned successfully
pxh> [2K
pxh> Exiting NOW.
Warning: could not find self.pem
Using local websockify at /opt/novnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
ERROR 2024-12-24 05:48:20,679 views 32 140351447678976 Command error - stderr: Connection closed by client.

WARNING: de57a1220d76:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server de57a1220d76:1
A VNC server is already running as :1
INFO 2024-12-24 05:48:20,680 views 32 140351447678976 Command return code: 0
INFO 2024-12-24 05:48:20,680 views 32 140351447678976 Container recent logs: INFO  [px4] Startup script returned successfully
pxh> [2K
pxh> Exiting NOW.
Warning: could not find self.pem
Using local websockify at /opt/novnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WARNING 2024-12-24 05:48:20,680 views 32 140351447678976 Container logs errors: Connection closed by client.

WARNING: de57a1220d76:1 is taken because of /tmp/.X11-unix/X1
Remove this file if there is no X server de57a1220d76:1
A VNC server is already running as :1
INFO 2024-12-24 05:48:20,745 views 32 140351447678976 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:48:20,771 views 32 140351447678976 Command output - stdout: 
ERROR 2024-12-24 05:48:20,772 views 32 140351447678976 Command error - stderr: "docker ps" accepts no arguments.
See 'docker ps --help'.

Usage:  docker ps [OPTIONS]

List containers
INFO 2024-12-24 05:48:20,772 views 32 140351447678976 Command return code: 1
ERROR 2024-12-24 05:49:07,886 exception 32 140351447678976 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-24 05:49:07,943 log 32 140351447678976 Bad Request: /
INFO 2024-12-24 05:52:48,235 views 241 140351447678976 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:52:48,258 views 241 140351447678976 Command output - stdout: 
INFO 2024-12-24 05:52:48,259 views 241 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,095 views 31 140351447678976 Received request to launch OpenUAV
INFO 2024-12-24 05:52:49,096 views 31 140351447678976 Checking if container already exists...
INFO 2024-12-24 05:52:49,096 views 31 140351447678976 Executing command: docker ps -a --filter name=openuav --format '{{.Names}}'
INFO 2024-12-24 05:52:49,125 views 31 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:52:49,126 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,126 views 31 140351447678976 Container exists, cleaning up and restarting...
INFO 2024-12-24 05:52:49,126 views 31 140351447678976 Executing command: docker stop openuav
INFO 2024-12-24 05:52:49,151 views 31 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:52:49,151 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,151 views 31 140351447678976 Executing command: docker rm openuav
INFO 2024-12-24 05:52:49,185 views 31 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:52:49,186 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,186 views 31 140351447678976 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-24 05:52:49,190 views 31 140351447678976 Command output - stdout: 
INFO 2024-12-24 05:52:49,190 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,190 views 31 140351447678976 Executing command: docker run -d --name openuav --privileged -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -v /tmp/.X11-unix:/tmp/.X11-unix:rw -e VNC_PASSWORD=liftoff openuav:px4-sitl
INFO 2024-12-24 05:52:49,548 views 31 140351447678976 Command output - stdout: 5dd8fe2791251ffd9c8f99822f9ae324cc2598c10271db327d1959ad6a7f02f7
INFO 2024-12-24 05:52:49,551 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:49,551 views 31 140351447678976 Container started successfully
INFO 2024-12-24 05:52:51,554 views 31 140351447678976 Executing command: docker inspect openuav --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-24 05:52:51,591 views 31 140351447678976 Command output - stdout: running true
INFO 2024-12-24 05:52:51,591 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:51,591 views 31 140351447678976 Container state: running true
INFO 2024-12-24 05:52:51,592 views 31 140351447678976 Executing command: docker logs openuav --tail 10
INFO 2024-12-24 05:52:51,622 views 31 140351447678976 Command output - stdout: Navigate to this URL:

    http://5dd8fe279125:6080/vnc.html?host=5dd8fe279125&port=6080

Press Ctrl-C to exit
ERROR 2024-12-24 05:52:51,622 views 31 140351447678976 Command error - stderr: - proxying from :6080 to localhost:5901
INFO 2024-12-24 05:52:51,622 views 31 140351447678976 Command return code: 0
INFO 2024-12-24 05:52:51,623 views 31 140351447678976 Container recent logs: Navigate to this URL:

    http://5dd8fe279125:6080/vnc.html?host=5dd8fe279125&port=6080

Press Ctrl-C to exit
WARNING 2024-12-24 05:52:51,623 views 31 140351447678976 Container logs errors: - proxying from :6080 to localhost:5901
INFO 2024-12-24 05:55:21,480 views 589 140351447678976 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:55:21,505 views 589 140351447678976 Command output - stdout: 
INFO 2024-12-24 05:55:21,505 views 589 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,294 views 33 140351447678976 Received request to launch OpenUAV
INFO 2024-12-24 05:55:22,294 views 33 140351447678976 Checking if container already exists...
INFO 2024-12-24 05:55:22,294 views 33 140351447678976 Executing command: docker ps -a --filter name=openuav --format '{{.Names}}'
INFO 2024-12-24 05:55:22,318 views 33 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:55:22,318 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,319 views 33 140351447678976 Container exists, cleaning up and restarting...
INFO 2024-12-24 05:55:22,319 views 33 140351447678976 Executing command: docker stop openuav
INFO 2024-12-24 05:55:22,342 views 33 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:55:22,342 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,342 views 33 140351447678976 Executing command: docker rm openuav
INFO 2024-12-24 05:55:22,376 views 33 140351447678976 Command output - stdout: openuav
INFO 2024-12-24 05:55:22,377 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,377 views 33 140351447678976 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-24 05:55:22,380 views 33 140351447678976 Command output - stdout: 
INFO 2024-12-24 05:55:22,380 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,381 views 33 140351447678976 Executing command: docker run -d --name openuav --privileged -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-24 05:55:22,747 views 33 140351447678976 Command output - stdout: 3ee7f843bdca390f08b46bfb8c2cf308bab61409ce8f252ac8b9448ad4ee0c8e
INFO 2024-12-24 05:55:22,747 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:22,747 views 33 140351447678976 Container started successfully
INFO 2024-12-24 05:55:27,753 views 33 140351447678976 Executing command: docker inspect openuav --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-24 05:55:27,791 views 33 140351447678976 Command output - stdout: running true
INFO 2024-12-24 05:55:27,791 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:27,791 views 33 140351447678976 Container state: running true
INFO 2024-12-24 05:55:27,791 views 33 140351447678976 Executing command: docker logs openuav --tail 20
INFO 2024-12-24 05:55:27,825 views 33 140351447678976 Command output - stdout: 2024-12-24 05:55:22,965 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:55:22,967 INFO supervisord started with pid 1
2024-12-24 05:55:23,970 INFO spawned: 'novnc' with pid 8
2024-12-24 05:55:23,973 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:55:23,976 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:55:24,018 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:55:24,095 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:55:25,007 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:55:26,011 INFO spawned: 'turbo_vnc' with pid 100
2024-12-24 05:55:26,014 INFO spawned: 'virtualgl' with pid 101
2024-12-24 05:55:26,053 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:55:26,132 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:55:27,825 views 33 140351447678976 Command return code: 0
INFO 2024-12-24 05:55:27,825 views 33 140351447678976 Container recent logs: 2024-12-24 05:55:22,965 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:55:22,967 INFO supervisord started with pid 1
2024-12-24 05:55:23,970 INFO spawned: 'novnc' with pid 8
2024-12-24 05:55:23,973 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:55:23,976 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:55:24,018 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:55:24,095 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:55:25,007 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:55:26,011 INFO spawned: 'turbo_vnc' with pid 100
2024-12-24 05:55:26,014 INFO spawned: 'virtualgl' with pid 101
2024-12-24 05:55:26,053 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:55:26,132 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:56:44,158 views 33 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:44,185 views 33 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:44,185 views 33 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:44,245 views 33 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:44,282 views 33 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:44,283 views 33 140626681675776 Command return code: 0
WARNING 2024-12-24 05:56:44,466 log 33 140626681675776 Not Found: /favicon.ico
INFO 2024-12-24 05:56:44,649 views 31 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:44,679 views 31 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:44,680 views 31 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:44,949 views 32 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:44,978 views 32 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:44,978 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:46,112 views 32 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:46,144 views 32 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:46,144 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:47,157 views 32 140626681675776 Received request to launch OpenUAV
INFO 2024-12-24 05:56:47,157 views 32 140626681675776 Checking if container already exists...
INFO 2024-12-24 05:56:47,158 views 32 140626681675776 Executing command: docker ps -a --filter name=openuav --format '{{.Names}}'
INFO 2024-12-24 05:56:47,191 views 32 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:47,191 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:47,191 views 32 140626681675776 Container does not exist, creating new container...
INFO 2024-12-24 05:56:47,191 views 32 140626681675776 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-24 05:56:47,195 views 32 140626681675776 Command output - stdout: 
INFO 2024-12-24 05:56:47,196 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:47,196 views 32 140626681675776 Executing command: docker run -d --name openuav --privileged -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-24 05:56:47,583 views 32 140626681675776 Command output - stdout: 89e7fb3eb84d90a7f678bcec468efb05b836af2e0b2044dbbcda90699bb0986f
INFO 2024-12-24 05:56:47,583 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:47,583 views 32 140626681675776 Container created with ID: 89e7fb3eb84d90a7f678bcec468efb05b836af2e0b2044dbbcda90699bb0986f
INFO 2024-12-24 05:56:47,583 views 32 140626681675776 Container started successfully
INFO 2024-12-24 05:56:52,589 views 32 140626681675776 Executing command: docker inspect openuav --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-24 05:56:52,628 views 32 140626681675776 Command output - stdout: running true
INFO 2024-12-24 05:56:52,628 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:52,629 views 32 140626681675776 Container state: running true
INFO 2024-12-24 05:56:52,629 views 32 140626681675776 Executing command: docker logs openuav --tail 20
INFO 2024-12-24 05:56:52,668 views 32 140626681675776 Command output - stdout: 2024-12-24 05:56:47,878 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:56:47,881 INFO supervisord started with pid 1
2024-12-24 05:56:48,884 INFO spawned: 'novnc' with pid 8
2024-12-24 05:56:48,887 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:56:48,891 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:56:48,931 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:56:49,007 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:56:49,924 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:56:50,852 INFO spawned: 'turbo_vnc' with pid 96
2024-12-24 05:56:50,855 INFO spawned: 'virtualgl' with pid 97
2024-12-24 05:56:50,894 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:56:50,974 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:56:52,668 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:56:52,668 views 32 140626681675776 Container recent logs: 2024-12-24 05:56:47,878 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:56:47,881 INFO supervisord started with pid 1
2024-12-24 05:56:48,884 INFO spawned: 'novnc' with pid 8
2024-12-24 05:56:48,887 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:56:48,891 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:56:48,931 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:56:49,007 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:56:49,924 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:56:50,852 INFO spawned: 'turbo_vnc' with pid 96
2024-12-24 05:56:50,855 INFO spawned: 'virtualgl' with pid 97
2024-12-24 05:56:50,894 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:56:50,974 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:56:52,723 views 32 140626681675776 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:56:52,759 views 32 140626681675776 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-24 05:56:47 +0000 UTC","ID":"89e7fb3eb84d","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"5 seconds ago","Size":"80.2kB (virtual 14GB)","State":"running","Status":"Up 5 seconds"}
INFO 2024-12-24 05:56:52,759 views 32 140626681675776 Command return code: 0
INFO 2024-12-24 05:58:48,889 views 32 139848044822528 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:58:48,915 views 32 139848044822528 Command output - stdout: 
INFO 2024-12-24 05:58:48,915 views 32 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:49,048 views 33 139848044822528 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:58:49,076 views 33 139848044822528 Command output - stdout: 
INFO 2024-12-24 05:58:49,076 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:51,473 views 33 139848044822528 Received request to launch OpenUAV
INFO 2024-12-24 05:58:51,474 views 33 139848044822528 Checking if container already exists...
INFO 2024-12-24 05:58:51,474 views 33 139848044822528 Executing command: docker ps -a --filter name=openuav --format '{{.Names}}'
INFO 2024-12-24 05:58:51,505 views 33 139848044822528 Command output - stdout: 
INFO 2024-12-24 05:58:51,505 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:51,505 views 33 139848044822528 Container does not exist, creating new container...
INFO 2024-12-24 05:58:51,505 views 33 139848044822528 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-24 05:58:51,509 views 33 139848044822528 Command output - stdout: 
INFO 2024-12-24 05:58:51,509 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:51,509 views 33 139848044822528 Executing command: docker run -d --name openuav --privileged -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-24 05:58:51,898 views 33 139848044822528 Command output - stdout: e7564e230f9bcb31e36fcd722ce086e902da80646126ad2744a3835f52653c5f
INFO 2024-12-24 05:58:51,898 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:51,898 views 33 139848044822528 Container created with ID: e7564e230f9bcb31e36fcd722ce086e902da80646126ad2744a3835f52653c5f
INFO 2024-12-24 05:58:51,898 views 33 139848044822528 Container started successfully
INFO 2024-12-24 05:58:56,904 views 33 139848044822528 Executing command: docker inspect openuav --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-24 05:58:56,944 views 33 139848044822528 Command output - stdout: running true
INFO 2024-12-24 05:58:56,945 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:56,945 views 33 139848044822528 Container state: running true
INFO 2024-12-24 05:58:56,945 views 33 139848044822528 Executing command: docker logs openuav --tail 20
INFO 2024-12-24 05:58:56,982 views 33 139848044822528 Command output - stdout: 2024-12-24 05:58:52,170 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:58:52,173 INFO supervisord started with pid 1
2024-12-24 05:58:53,176 INFO spawned: 'novnc' with pid 8
2024-12-24 05:58:53,179 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:58:53,182 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:58:53,222 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:58:53,299 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:58:54,214 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:58:55,217 INFO spawned: 'turbo_vnc' with pid 93
2024-12-24 05:58:55,221 INFO spawned: 'virtualgl' with pid 94
2024-12-24 05:58:55,260 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:58:55,338 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:58:56,982 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:58:56,983 views 33 139848044822528 Container recent logs: 2024-12-24 05:58:52,170 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-24 05:58:52,173 INFO supervisord started with pid 1
2024-12-24 05:58:53,176 INFO spawned: 'novnc' with pid 8
2024-12-24 05:58:53,179 INFO spawned: 'turbo_vnc' with pid 9
2024-12-24 05:58:53,182 INFO spawned: 'virtualgl' with pid 10
2024-12-24 05:58:53,222 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:58:53,299 INFO exited: virtualgl (exit status 0; not expected)
2024-12-24 05:58:54,214 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-24 05:58:55,217 INFO spawned: 'turbo_vnc' with pid 93
2024-12-24 05:58:55,221 INFO spawned: 'virtualgl' with pid 94
2024-12-24 05:58:55,260 INFO exited: turbo_vnc (exit status 2; not expected)
2024-12-24 05:58:55,338 INFO exited: virtualgl (exit status 0; not expected)
INFO 2024-12-24 05:58:57,014 views 33 139848044822528 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:58:57,050 views 33 139848044822528 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-24 05:58:51 +0000 UTC","ID":"e7564e230f9b","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"6 seconds ago","Size":"78.8kB (virtual 14GB)","State":"running","Status":"Up 5 seconds"}
INFO 2024-12-24 05:58:57,051 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:59:11,717 views 33 139848044822528 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:59:11,758 views 33 139848044822528 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-24 05:58:51 +0000 UTC","ID":"e7564e230f9b","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"20 seconds ago","Size":"83.5kB (virtual 14GB)","State":"running","Status":"Up 20 seconds"}
INFO 2024-12-24 05:59:11,758 views 33 139848044822528 Command return code: 0
INFO 2024-12-24 05:59:13,387 views 33 139848044822528 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-24 05:59:13,425 views 33 139848044822528 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-24 05:58:51 +0000 UTC","ID":"e7564e230f9b","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"22 seconds ago","Size":"83.5kB (virtual 14GB)","State":"running","Status":"Up 21 seconds"}
INFO 2024-12-24 05:59:13,425 views 33 139848044822528 Command return code: 0
WARNING 2024-12-24 05:59:44,549 log 33 139848044822528 Not Found: /None
WARNING 2024-12-24 05:59:44,622 log 33 139848044822528 Not Found: /static/images/planetary_background.jpg
ERROR 2024-12-25 04:31:59,862 exception 285 140648106434560 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:31:59,922 log 285 140648106434560 Bad Request: /
WARNING 2024-12-25 04:32:01,435 log 286 140648106434560 Not Found: /logon.htm
ERROR 2024-12-25 04:44:04,591 exception 286 140648106434560 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:44:04,645 log 286 140648106434560 Bad Request: /
ERROR 2024-12-25 04:44:04,961 exception 286 140648106434560 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:44:05,007 log 286 140648106434560 Bad Request: /443
ERROR 2024-12-25 04:44:05,340 exception 286 140648106434560 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:44:05,388 log 286 140648106434560 Bad Request: /
ERROR 2024-12-25 04:44:05,710 exception 286 140648106434560 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:44:05,755 log 286 140648106434560 Bad Request: /443
ERROR 2024-12-25 04:52:49,954 exception 286 140648106434560 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 04:52:50,004 log 286 140648106434560 Bad Request: /goform/set_LimitClient_cfg
WARNING 2024-12-25 05:59:09,817 log 30 140095638204416 Not Found: /None
WARNING 2024-12-25 05:59:09,915 log 30 140095638204416 Not Found: /static/images/planetary_background.jpg
INFO 2024-12-25 05:59:13,621 views 30 140095638204416 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 05:59:13,666 views 30 140095638204416 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-24 17:30:17 +0000 UTC","ID":"106e6f7aaf22","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"12 hours ago","Size":"686kB (virtual 14GB)","State":"running","Status":"Up 12 hours"}
INFO 2024-12-25 05:59:13,667 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:15,538 views 30 140095638204416 Executing command: docker stop openuav
INFO 2024-12-25 05:59:17,767 views 30 140095638204416 Command output - stdout: openuav
INFO 2024-12-25 05:59:17,768 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:17,768 views 30 140095638204416 Executing command: docker rm openuav
INFO 2024-12-25 05:59:17,811 views 30 140095638204416 Command output - stdout: openuav
INFO 2024-12-25 05:59:17,811 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:17,811 views 30 140095638204416 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 05:59:17,815 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:17,815 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:17,831 views 30 140095638204416 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 05:59:17,860 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:17,861 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:19,256 views 30 140095638204416 Received request to launch OpenUAV
INFO 2024-12-25 05:59:19,256 views 30 140095638204416 Launching container with name: openuav-f1e3abbf
INFO 2024-12-25 05:59:19,257 views 30 140095638204416 Checking if container already exists...
INFO 2024-12-25 05:59:19,257 views 30 140095638204416 Executing command: docker ps -a --filter name=openuav-f1e3abbf --format '{{.Names}}'
INFO 2024-12-25 05:59:19,291 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:19,291 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:19,292 views 30 140095638204416 Cleaning up stale files...
INFO 2024-12-25 05:59:19,292 views 30 140095638204416 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 05:59:19,295 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:19,296 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:19,296 views 30 140095638204416 Executing command: rm -f /tmp/.X1*
INFO 2024-12-25 05:59:19,299 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:19,299 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:19,299 views 30 140095638204416 Executing command: pkill -f Xvnc || true
INFO 2024-12-25 05:59:19,306 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:19,307 views 30 140095638204416 Command return code: -15
INFO 2024-12-25 05:59:19,307 views 30 140095638204416 Executing command: pkill -f vncserver || true
INFO 2024-12-25 05:59:19,312 views 30 140095638204416 Command output - stdout: 
INFO 2024-12-25 05:59:19,312 views 30 140095638204416 Command return code: -15
INFO 2024-12-25 05:59:19,313 views 30 140095638204416 Creating new container...
INFO 2024-12-25 05:59:19,313 views 30 140095638204416 Executing command: docker run -d --name openuav-f1e3abbf --privileged --gpus all -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-25 05:59:20,314 views 30 140095638204416 Command output - stdout: cb26a9dab49f688179c9b1d869fedd9d1aea030927a28003f7c25a9783730621
INFO 2024-12-25 05:59:20,315 views 30 140095638204416 Command return code: 0
INFO 2024-12-25 05:59:20,315 views 30 140095638204416 Container started successfully
INFO 2024-12-25 05:59:25,320 views 30 140095638204416 Executing command: docker inspect --format='{{.Id}}' openuav-f1e3abbf
INFO 2024-12-25 05:59:25,359 views 30 140095638204416 Command output - stdout: cb26a9dab49f688179c9b1d869fedd9d1aea030927a28003f7c25a9783730621
INFO 2024-12-25 05:59:25,360 views 30 140095638204416 Command return code: 0
ERROR 2024-12-25 05:59:25,366 views 30 140095638204416 Exception in launch_openuav: no such table: openuav_manager_container
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: openuav_manager_container

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/openuav_manager/views.py", line 190, in launch_openuav
    container = Container.objects.create(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: openuav_manager_container
ERROR 2024-12-25 05:59:25,369 log 30 140095638204416 Internal Server Error: /openuav/launch/
ERROR 2024-12-25 06:28:53,101 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 06:28:53,160 log 1177 140351621001216 Bad Request: /
WARNING 2024-12-25 06:28:54,638 log 1177 140351621001216 Not Found: /logon.htm
ERROR 2024-12-25 06:35:42,163 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 06:35:42,223 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 06:48:29,560 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 06:48:29,625 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 07:04:11,964 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:04:12,012 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 07:12:18,308 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:12:18,355 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 07:13:28,065 exception 1176 140351621001216 Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:13:28,112 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 07:13:51,494 exception 1176 140351621001216 Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:13:51,540 log 1176 140351621001216 Bad Request: /443
ERROR 2024-12-25 07:14:14,475 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:14:14,522 log 1176 140351621001216 Bad Request: /geoserver/web/
ERROR 2024-12-25 07:43:16,364 exception 1175 140351621001216 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:43:16,412 log 1175 140351621001216 Bad Request: /443
ERROR 2024-12-25 07:50:50,203 exception 1176 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:50:50,250 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 07:52:23,840 exception 1176 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:52:23,886 log 1176 140351621001216 Bad Request: /443
ERROR 2024-12-25 07:57:18,655 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:57:18,702 log 1176 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 07:59:08,057 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 07:59:08,104 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 08:20:14,831 exception 1177 140351621001216 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 08:20:14,882 log 1177 140351621001216 Bad Request: /443
ERROR 2024-12-25 08:31:17,434 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 08:31:17,482 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 08:35:00,278 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 08:35:00,326 log 1176 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 08:37:55,284 exception 1175 140351621001216 Invalid HTTP_HOST header: 'term-3.openuav.us'. You may need to add 'term-3.openuav.us' to ALLOWED_HOSTS.
WARNING 2024-12-25 08:37:55,333 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 09:27:53,987 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 09:27:54,038 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 09:41:13,599 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 09:41:13,649 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 09:41:14,447 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 09:41:14,494 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 09:41:15,217 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 09:41:15,262 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 10:14:19,452 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:14:19,499 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 10:14:19,825 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:14:19,870 log 1175 140351621001216 Bad Request: /443
ERROR 2024-12-25 10:14:20,190 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:14:20,236 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 10:14:20,558 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:14:20,602 log 1175 140351621001216 Bad Request: /443
ERROR 2024-12-25 10:14:59,444 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:14:59,490 log 1175 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 10:38:01,389 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:38:01,437 log 1177 140351621001216 Bad Request: /
ERROR 2024-12-25 10:41:23,649 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 10:41:23,708 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 11:17:53,733 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:17:53,784 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 11:17:54,789 exception 1176 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:17:54,839 log 1176 140351621001216 Bad Request: /443
ERROR 2024-12-25 11:17:55,171 exception 1176 140351621001216 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:17:55,216 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 11:17:55,543 exception 1176 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:17:55,598 log 1176 140351621001216 Bad Request: /443
ERROR 2024-12-25 11:24:22,764 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:24:22,818 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 11:26:02,454 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:26:02,502 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 11:26:03,369 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:26:03,417 log 1177 140351621001216 Bad Request: /favicon.ico
ERROR 2024-12-25 11:26:03,781 exception 1175 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
ERROR 2024-12-25 11:26:03,788 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:26:03,827 log 1175 140351621001216 Bad Request: /sitemap.xml
WARNING 2024-12-25 11:26:03,835 log 1176 140351621001216 Bad Request: /robots.txt
ERROR 2024-12-25 11:28:15,765 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:28:15,813 log 1175 140351621001216 Bad Request: /
ERROR 2024-12-25 11:45:54,380 exception 1177 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:45:54,428 log 1177 140351621001216 Bad Request: /443
ERROR 2024-12-25 11:57:49,317 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 11:57:49,364 log 1176 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 12:18:42,150 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 12:18:42,187 log 1176 140351621001216 Bad Request: /
ERROR 2024-12-25 12:40:01,105 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 12:40:01,157 log 1177 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 14:01:57,747 exception 1176 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:01:57,793 log 1176 140351621001216 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 14:27:10,667 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:10,717 log 1175 140351621001216 Bad Request: /phpMyAdmin/scripts/setup.php
ERROR 2024-12-25 14:27:11,091 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:11,138 log 1175 140351621001216 Bad Request: /phpmyadmin/scripts/setup.php
ERROR 2024-12-25 14:27:11,518 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:11,564 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.11.4/scripts/setup.php
ERROR 2024-12-25 14:27:11,932 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:11,977 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.11.3/scripts/setup.php
ERROR 2024-12-25 14:27:12,334 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:12,381 log 1177 140351621001216 Bad Request: /phpMyAdmin-2.10.0.2/scripts/setup.php
ERROR 2024-12-25 14:27:12,746 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:12,793 log 1177 140351621001216 Bad Request: /phpMyAdmin-2.10.3/scripts/setup.php
ERROR 2024-12-25 14:27:13,171 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:13,217 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.8.0.2/scripts/setup.php
ERROR 2024-12-25 14:27:13,597 exception 1176 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:13,644 log 1176 140351621001216 Bad Request: /phpMyAdmin-2.10.2/scripts/setup.php
ERROR 2024-12-25 14:27:14,027 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:14,074 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.11.9.2/scripts/setup.php
ERROR 2024-12-25 14:27:14,435 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:14,481 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.11.0/scripts/setup.php
ERROR 2024-12-25 14:27:14,845 exception 1175 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:14,892 log 1175 140351621001216 Bad Request: /phpMyAdmin-2.11.7/scripts/setup.php
ERROR 2024-12-25 14:27:15,259 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:15,305 log 1177 140351621001216 Bad Request: /phpMyAdmin-2.11.1.2/scripts/setup.php
ERROR 2024-12-25 14:27:15,671 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:15,798 log 1177 140351621001216 Bad Request: /pma/scripts/setup.php
ERROR 2024-12-25 14:27:16,179 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:16,225 log 1177 140351621001216 Bad Request: /phpMyAdmin3/scripts/setup.php
ERROR 2024-12-25 14:27:16,606 exception 1177 140351621001216 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:27:16,652 log 1177 140351621001216 Bad Request: /myadmin/scripts/setup.php
ERROR 2024-12-25 14:36:03,599 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:36:03,649 log 1177 140351621001216 Bad Request: /
ERROR 2024-12-25 14:40:26,762 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:40:26,813 log 1177 140351621001216 Bad Request: /
ERROR 2024-12-25 14:44:35,790 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:44:35,838 log 1177 140351621001216 Bad Request: /
ERROR 2024-12-25 14:47:08,445 exception 1177 140351621001216 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 14:47:08,493 log 1177 140351621001216 Bad Request: /
ERROR 2024-12-25 15:50:00,664 exception 1175 140351621001216 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 15:50:00,712 log 1175 140351621001216 Bad Request: /443
ERROR 2024-12-25 16:20:52,582 exception 1176 140351621001216 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 16:20:52,630 log 1176 140351621001216 Bad Request: /443
WARNING 2024-12-25 16:28:57,906 log 1050 140122105278464 Not Found: /favicon.ico
ERROR 2024-12-25 16:38:03,804 exception 1050 140122105278464 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 16:38:03,911 log 1050 140122105278464 Bad Request: /cgi-bin/luci/;stok=/locale
INFO 2024-12-25 16:44:03,713 views 1049 140122105278464 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 16:44:03,757 views 1049 140122105278464 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 05:59:19 +0000 UTC","ID":"cb26a9dab49f","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-f1e3abbf","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"11 hours ago","Size":"515kB (virtual 14GB)","State":"running","Status":"Up 11 hours"}
INFO 2024-12-25 16:44:03,757 views 1049 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:05,410 views 1049 140122105278464 Executing command: docker stop openuav
INFO 2024-12-25 16:44:05,443 views 1049 140122105278464 Command output - stdout: 
ERROR 2024-12-25 16:44:05,443 views 1049 140122105278464 Command error - stderr: Error response from daemon: No such container: openuav
INFO 2024-12-25 16:44:05,443 views 1049 140122105278464 Command return code: 1
ERROR 2024-12-25 16:44:05,444 log 1049 140122105278464 Internal Server Error: /openuav/stop/
INFO 2024-12-25 16:44:10,028 views 1049 140122105278464 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 16:44:10,071 views 1049 140122105278464 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 05:59:19 +0000 UTC","ID":"cb26a9dab49f","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-f1e3abbf","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"11 hours ago","Size":"515kB (virtual 14GB)","State":"running","Status":"Up 11 hours"}
INFO 2024-12-25 16:44:10,071 views 1049 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:49,045 views 1048 140122105278464 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 16:44:49,082 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:49,082 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:50,822 views 1048 140122105278464 Received request to launch OpenUAV
INFO 2024-12-25 16:44:50,823 views 1048 140122105278464 Launching container with name: openuav-3ad74990
INFO 2024-12-25 16:44:50,823 views 1048 140122105278464 Checking if container already exists...
INFO 2024-12-25 16:44:50,823 views 1048 140122105278464 Executing command: docker ps -a --filter name=openuav-3ad74990 --format '{{.Names}}'
INFO 2024-12-25 16:44:50,856 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:50,856 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:50,857 views 1048 140122105278464 Cleaning up stale files...
INFO 2024-12-25 16:44:50,857 views 1048 140122105278464 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 16:44:50,860 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:50,860 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:50,861 views 1048 140122105278464 Executing command: rm -f /tmp/.X1*
INFO 2024-12-25 16:44:50,864 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:50,864 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:50,864 views 1048 140122105278464 Executing command: pkill -f Xvnc || true
INFO 2024-12-25 16:44:50,870 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:50,870 views 1048 140122105278464 Command return code: -15
INFO 2024-12-25 16:44:50,870 views 1048 140122105278464 Executing command: pkill -f vncserver || true
INFO 2024-12-25 16:44:50,876 views 1048 140122105278464 Command output - stdout: 
INFO 2024-12-25 16:44:50,876 views 1048 140122105278464 Command return code: -15
INFO 2024-12-25 16:44:50,877 views 1048 140122105278464 Creating new container...
INFO 2024-12-25 16:44:50,877 views 1048 140122105278464 Executing command: docker run -d --name openuav-3ad74990 --privileged --gpus all -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-25 16:44:51,832 views 1048 140122105278464 Command output - stdout: f1dca70e2cd94161732ee31c46e285b2dafd22eeeab8fa7acf7f753842734489
INFO 2024-12-25 16:44:51,832 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:51,832 views 1048 140122105278464 Container started successfully
INFO 2024-12-25 16:44:56,837 views 1048 140122105278464 Executing command: docker inspect --format='{{.Id}}' openuav-3ad74990
INFO 2024-12-25 16:44:56,878 views 1048 140122105278464 Command output - stdout: f1dca70e2cd94161732ee31c46e285b2dafd22eeeab8fa7acf7f753842734489
INFO 2024-12-25 16:44:56,879 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:56,889 views 1048 140122105278464 Executing command: docker inspect openuav-3ad74990 --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-25 16:44:56,922 views 1048 140122105278464 Command output - stdout: running true
INFO 2024-12-25 16:44:56,922 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:56,923 views 1048 140122105278464 Container state: running true
INFO 2024-12-25 16:44:56,923 views 1048 140122105278464 Executing command: docker exec openuav-3ad74990 ps aux | grep Xvnc
INFO 2024-12-25 16:44:57,010 views 1048 140122105278464 Command output - stdout: root          50  3.7  0.0 167056 64640 ?        S    16:44   0:00 /opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: f1dca70e2cd9:1 () -auth /root/.Xauthority -geometry 1920x1080 -depth 24 -rfbauth /root/.vnc/passwd -x509cert /root/.vnc/x509_cert.pem -x509key /root/.vnc/x509_private.pem -rfbport 5901 -fp /usr/share/fonts/X11/misc -deferupdate 1 -dridir /usr/lib/x86_64-linux-gnu/dri -registrydir /usr/lib/xorg
INFO 2024-12-25 16:44:57,010 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:57,010 views 1048 140122105278464 Executing command: docker logs openuav-3ad74990 --tail 20
INFO 2024-12-25 16:44:57,045 views 1048 140122105278464 Command output - stdout: 2024-12-25 16:44:53,108 INFO spawned: 'cleanup' with pid 20
2024-12-25 16:44:53,111 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 16:44:53,114 INFO spawned: 'novnc' with pid 22
2024-12-25 16:44:53,117 INFO spawned: 'virtualgl' with pid 23
2024-12-25 16:44:53,119 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 16:44:53,119 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 16:44:53,239 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 16:44:54,162 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 16:44:54,163 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 16:44:54,167 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 16:44:55,171 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 16:44:55,174 INFO spawned: 'virtualgl' with pid 250
2024-12-25 16:44:55,175 INFO reaped unknown pid 154
2024-12-25 16:44:55,175 INFO reaped unknown pid 161
2024-12-25 16:44:55,175 INFO reaped unknown pid 165
2024-12-25 16:44:55,175 INFO reaped unknown pid 172
2024-12-25 16:44:55,213 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 16:44:55,290 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 16:44:56,294 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 16:44:56,336 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 16:44:57,046 views 1048 140122105278464 Command return code: 0
INFO 2024-12-25 16:44:57,046 views 1048 140122105278464 Container recent logs: 2024-12-25 16:44:53,108 INFO spawned: 'cleanup' with pid 20
2024-12-25 16:44:53,111 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 16:44:53,114 INFO spawned: 'novnc' with pid 22
2024-12-25 16:44:53,117 INFO spawned: 'virtualgl' with pid 23
2024-12-25 16:44:53,119 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 16:44:53,119 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 16:44:53,239 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 16:44:54,162 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 16:44:54,163 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 16:44:54,167 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 16:44:55,171 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 16:44:55,174 INFO spawned: 'virtualgl' with pid 250
2024-12-25 16:44:55,175 INFO reaped unknown pid 154
2024-12-25 16:44:55,175 INFO reaped unknown pid 161
2024-12-25 16:44:55,175 INFO reaped unknown pid 165
2024-12-25 16:44:55,175 INFO reaped unknown pid 172
2024-12-25 16:44:55,213 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 16:44:55,290 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 16:44:56,294 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 16:44:56,336 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 16:44:57,058 views 1048 140122105278464 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 16:44:57,103 views 1048 140122105278464 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 16:44:50 +0000 UTC","ID":"f1dca70e2cd9","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-3ad74990","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"7 seconds ago","Size":"429kB (virtual 14GB)","State":"running","Status":"Up 6 seconds"}
INFO 2024-12-25 16:44:57,103 views 1048 140122105278464 Command return code: 0
WARNING 2024-12-25 16:47:39,535 log 32 139779472371712 Not Found: /openuav_manager/admin/
WARNING 2024-12-25 16:47:46,365 log 31 139779472371712 Not Found: /favicon.ico
INFO 2024-12-25 16:51:13,765 views 31 140716401926144 Executing command: docker stop openuav
INFO 2024-12-25 16:51:13,790 views 31 140716401926144 Command output - stdout: 
ERROR 2024-12-25 16:51:13,790 views 31 140716401926144 Command error - stderr: Error response from daemon: No such container: openuav
INFO 2024-12-25 16:51:13,790 views 31 140716401926144 Command return code: 1
ERROR 2024-12-25 16:51:13,791 log 31 140716401926144 Internal Server Error: /openuav/stop/
INFO 2024-12-25 16:56:51,114 views 33 140716401926144 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 16:56:51,159 views 33 140716401926144 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 16:44:50 +0000 UTC","ID":"f1dca70e2cd9","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-3ad74990","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"12 minutes ago","Size":"513kB (virtual 14GB)","State":"running","Status":"Up 12 minutes"}
INFO 2024-12-25 16:56:51,160 views 33 140716401926144 Command return code: 0
INFO 2024-12-25 16:57:11,815 views 33 140716401926144 Executing command: docker stop openuav
INFO 2024-12-25 16:57:11,848 views 33 140716401926144 Command output - stdout: 
ERROR 2024-12-25 16:57:11,848 views 33 140716401926144 Command error - stderr: Error response from daemon: No such container: openuav
INFO 2024-12-25 16:57:11,848 views 33 140716401926144 Command return code: 1
ERROR 2024-12-25 16:57:11,849 log 33 140716401926144 Internal Server Error: /openuav/stop/
INFO 2024-12-25 16:57:14,783 views 31 140716401926144 Executing command: docker stop openuav
INFO 2024-12-25 16:57:14,813 views 31 140716401926144 Command output - stdout: 
ERROR 2024-12-25 16:57:14,813 views 31 140716401926144 Command error - stderr: Error response from daemon: No such container: openuav
INFO 2024-12-25 16:57:14,814 views 31 140716401926144 Command return code: 1
ERROR 2024-12-25 16:57:14,814 log 31 140716401926144 Internal Server Error: /openuav/stop/
INFO 2024-12-25 17:04:11,831 views 32 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:04:11,858 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:04:11,858 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 17:04:14,201 views 31 140235855441920 Received request to launch OpenUAV
ERROR 2024-12-25 17:04:14,209 views 31 140235855441920 Exception in launch_openuav: no such column: openuav_manager_container.session_type
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: openuav_manager_container.session_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/openuav_manager/views.py", line 143, in launch_openuav
    existing_container = Container.objects.filter(**session_filter).first()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 674, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: openuav_manager_container.session_type
ERROR 2024-12-25 17:04:14,211 log 31 140235855441920 Internal Server Error: /openuav/launch/
ERROR 2024-12-25 17:04:44,599 exception 31 140235855441920 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 17:04:44,661 log 31 140235855441920 Bad Request: /443
INFO 2024-12-25 17:05:39,220 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:05:39,255 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:39,255 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:40,593 views 31 140235855441920 Received request to launch OpenUAV
INFO 2024-12-25 17:05:40,603 views 31 140235855441920 Launching container with name: openuav-cb95302b
INFO 2024-12-25 17:05:40,603 views 31 140235855441920 Checking if container already exists...
INFO 2024-12-25 17:05:40,604 views 31 140235855441920 Executing command: docker ps -a --filter name=openuav-cb95302b --format '{{.Names}}'
INFO 2024-12-25 17:05:40,637 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:40,637 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:40,637 views 31 140235855441920 Cleaning up stale files...
INFO 2024-12-25 17:05:40,638 views 31 140235855441920 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 17:05:40,641 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:40,642 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:40,642 views 31 140235855441920 Executing command: rm -f /tmp/.X1*
INFO 2024-12-25 17:05:40,646 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:40,646 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:40,646 views 31 140235855441920 Executing command: pkill -f Xvnc || true
INFO 2024-12-25 17:05:40,653 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:40,653 views 31 140235855441920 Command return code: -15
INFO 2024-12-25 17:05:40,653 views 31 140235855441920 Executing command: pkill -f vncserver || true
INFO 2024-12-25 17:05:40,659 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:05:40,659 views 31 140235855441920 Command return code: -15
INFO 2024-12-25 17:05:40,659 views 31 140235855441920 Creating new container...
INFO 2024-12-25 17:05:40,660 views 31 140235855441920 Executing command: docker run -d --name openuav-cb95302b --privileged --gpus all -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-25 17:05:41,596 views 31 140235855441920 Command output - stdout: d4585549aec285613cbfc72f5b9ec5ec40c5d0954c75fe3b5400e799412c7332
INFO 2024-12-25 17:05:41,596 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:41,596 views 31 140235855441920 Container started successfully
INFO 2024-12-25 17:05:46,602 views 31 140235855441920 Executing command: docker inspect --format='{{.Id}}' openuav-cb95302b
INFO 2024-12-25 17:05:46,641 views 31 140235855441920 Command output - stdout: d4585549aec285613cbfc72f5b9ec5ec40c5d0954c75fe3b5400e799412c7332
INFO 2024-12-25 17:05:46,641 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:46,649 views 31 140235855441920 Executing command: docker inspect openuav-cb95302b --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-25 17:05:46,685 views 31 140235855441920 Command output - stdout: running true
INFO 2024-12-25 17:05:46,685 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:46,685 views 31 140235855441920 Container state: running true
INFO 2024-12-25 17:05:46,685 views 31 140235855441920 Executing command: docker exec openuav-cb95302b ps aux | grep Xvnc
INFO 2024-12-25 17:05:46,775 views 31 140235855441920 Command output - stdout: root          50  3.7  0.0 167056 64048 ?        S    17:05   0:00 /opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: d4585549aec2:1 () -auth /root/.Xauthority -geometry 1920x1080 -depth 24 -rfbauth /root/.vnc/passwd -x509cert /root/.vnc/x509_cert.pem -x509key /root/.vnc/x509_private.pem -rfbport 5901 -fp /usr/share/fonts/X11/misc -deferupdate 1 -dridir /usr/lib/x86_64-linux-gnu/dri -registrydir /usr/lib/xorg
INFO 2024-12-25 17:05:46,775 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:46,775 views 31 140235855441920 Executing command: docker logs openuav-cb95302b --tail 20
INFO 2024-12-25 17:05:46,806 views 31 140235855441920 Command output - stdout: 2024-12-25 17:05:42,882 INFO spawned: 'cleanup' with pid 20
2024-12-25 17:05:42,885 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 17:05:42,888 INFO spawned: 'novnc' with pid 22
2024-12-25 17:05:42,891 INFO spawned: 'virtualgl' with pid 23
2024-12-25 17:05:42,894 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 17:05:42,894 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 17:05:43,010 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:05:43,941 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:05:43,941 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:05:43,946 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 17:05:44,950 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 17:05:44,953 INFO spawned: 'virtualgl' with pid 250
2024-12-25 17:05:44,954 INFO reaped unknown pid 154
2024-12-25 17:05:44,954 INFO reaped unknown pid 162
2024-12-25 17:05:44,954 INFO reaped unknown pid 167
2024-12-25 17:05:44,954 INFO reaped unknown pid 172
2024-12-25 17:05:44,994 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 17:05:45,068 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:05:46,072 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 17:05:46,113 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 17:05:46,806 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:05:46,807 views 31 140235855441920 Container recent logs: 2024-12-25 17:05:42,882 INFO spawned: 'cleanup' with pid 20
2024-12-25 17:05:42,885 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 17:05:42,888 INFO spawned: 'novnc' with pid 22
2024-12-25 17:05:42,891 INFO spawned: 'virtualgl' with pid 23
2024-12-25 17:05:42,894 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 17:05:42,894 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 17:05:43,010 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:05:43,941 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:05:43,941 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:05:43,946 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 17:05:44,950 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 17:05:44,953 INFO spawned: 'virtualgl' with pid 250
2024-12-25 17:05:44,954 INFO reaped unknown pid 154
2024-12-25 17:05:44,954 INFO reaped unknown pid 162
2024-12-25 17:05:44,954 INFO reaped unknown pid 167
2024-12-25 17:05:44,954 INFO reaped unknown pid 172
2024-12-25 17:05:44,994 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 17:05:45,068 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:05:46,072 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 17:05:46,113 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 17:05:46,819 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:05:46,856 views 31 140235855441920 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 17:05:40 +0000 UTC","ID":"d4585549aec2","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-cb95302b","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"6 seconds ago","Size":"429kB (virtual 14GB)","State":"running","Status":"Up 6 seconds"}
INFO 2024-12-25 17:05:46,856 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:08,644 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:06:08,688 views 31 140235855441920 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 17:05:40 +0000 UTC","ID":"d4585549aec2","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-cb95302b","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"28 seconds ago","Size":"514kB (virtual 14GB)","State":"running","Status":"Up 27 seconds"}
INFO 2024-12-25 17:06:08,688 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:11,794 views 31 140235855441920 Stopping container: openuav-cb95302b
INFO 2024-12-25 17:06:11,794 views 31 140235855441920 Executing command: docker stop openuav-cb95302b
INFO 2024-12-25 17:06:13,520 views 31 140235855441920 Command output - stdout: openuav-cb95302b
INFO 2024-12-25 17:06:13,521 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:13,521 views 31 140235855441920 Executing command: docker rm openuav-cb95302b
INFO 2024-12-25 17:06:13,570 views 31 140235855441920 Command output - stdout: openuav-cb95302b
INFO 2024-12-25 17:06:13,571 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:13,579 views 31 140235855441920 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 17:06:13,583 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:13,583 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:13,604 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:06:13,636 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:13,636 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:27,160 views 31 140235855441920 Received request to launch OpenUAV
INFO 2024-12-25 17:06:27,170 views 31 140235855441920 Launching container with name: openuav-a69e5db2
INFO 2024-12-25 17:06:27,170 views 31 140235855441920 Checking if container already exists...
INFO 2024-12-25 17:06:27,170 views 31 140235855441920 Executing command: docker ps -a --filter name=openuav-a69e5db2 --format '{{.Names}}'
INFO 2024-12-25 17:06:27,204 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:27,204 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:27,204 views 31 140235855441920 Cleaning up stale files...
INFO 2024-12-25 17:06:27,205 views 31 140235855441920 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 17:06:27,208 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:27,208 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:27,209 views 31 140235855441920 Executing command: rm -f /tmp/.X1*
INFO 2024-12-25 17:06:27,212 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:27,212 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:27,213 views 31 140235855441920 Executing command: pkill -f Xvnc || true
INFO 2024-12-25 17:06:27,218 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:27,219 views 31 140235855441920 Command return code: -15
INFO 2024-12-25 17:06:27,219 views 31 140235855441920 Executing command: pkill -f vncserver || true
INFO 2024-12-25 17:06:27,225 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:27,225 views 31 140235855441920 Command return code: -15
INFO 2024-12-25 17:06:27,225 views 31 140235855441920 Creating new container...
INFO 2024-12-25 17:06:27,225 views 31 140235855441920 Executing command: docker run -d --name openuav-a69e5db2 --privileged --gpus all -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-25 17:06:28,185 views 31 140235855441920 Command output - stdout: 4b0d3026fa7c8506f1a8bee961cb2fd0805f045f1034b66de5fd2ee04501cfc6
INFO 2024-12-25 17:06:28,185 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:28,185 views 31 140235855441920 Container started successfully
INFO 2024-12-25 17:06:33,190 views 31 140235855441920 Executing command: docker inspect --format='{{.Id}}' openuav-a69e5db2
INFO 2024-12-25 17:06:33,231 views 31 140235855441920 Command output - stdout: 4b0d3026fa7c8506f1a8bee961cb2fd0805f045f1034b66de5fd2ee04501cfc6
INFO 2024-12-25 17:06:33,231 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:33,237 views 31 140235855441920 Executing command: docker inspect openuav-a69e5db2 --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-25 17:06:33,271 views 31 140235855441920 Command output - stdout: running true
INFO 2024-12-25 17:06:33,271 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:33,271 views 31 140235855441920 Container state: running true
INFO 2024-12-25 17:06:33,271 views 31 140235855441920 Executing command: docker exec openuav-a69e5db2 ps aux | grep Xvnc
INFO 2024-12-25 17:06:33,359 views 31 140235855441920 Command output - stdout: root          50  3.7  0.0 167096 63636 ?        S    17:06   0:00 /opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: 4b0d3026fa7c:1 () -auth /root/.Xauthority -geometry 1920x1080 -depth 24 -rfbauth /root/.vnc/passwd -x509cert /root/.vnc/x509_cert.pem -x509key /root/.vnc/x509_private.pem -rfbport 5901 -fp /usr/share/fonts/X11/misc -deferupdate 1 -dridir /usr/lib/x86_64-linux-gnu/dri -registrydir /usr/lib/xorg
INFO 2024-12-25 17:06:33,359 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:33,360 views 31 140235855441920 Executing command: docker logs openuav-a69e5db2 --tail 20
INFO 2024-12-25 17:06:33,399 views 31 140235855441920 Command output - stdout: 2024-12-25 17:06:29,457 INFO spawned: 'cleanup' with pid 20
2024-12-25 17:06:29,461 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 17:06:29,464 INFO spawned: 'novnc' with pid 22
2024-12-25 17:06:29,466 INFO spawned: 'virtualgl' with pid 23
2024-12-25 17:06:29,469 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 17:06:29,469 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 17:06:29,587 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:06:30,514 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:06:30,514 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:06:30,518 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 17:06:31,522 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 17:06:31,525 INFO spawned: 'virtualgl' with pid 250
2024-12-25 17:06:31,526 INFO reaped unknown pid 154
2024-12-25 17:06:31,526 INFO reaped unknown pid 161
2024-12-25 17:06:31,526 INFO reaped unknown pid 166
2024-12-25 17:06:31,526 INFO reaped unknown pid 174
2024-12-25 17:06:31,568 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 17:06:31,647 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:06:32,651 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 17:06:32,694 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 17:06:33,399 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:33,399 views 31 140235855441920 Container recent logs: 2024-12-25 17:06:29,457 INFO spawned: 'cleanup' with pid 20
2024-12-25 17:06:29,461 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 17:06:29,464 INFO spawned: 'novnc' with pid 22
2024-12-25 17:06:29,466 INFO spawned: 'virtualgl' with pid 23
2024-12-25 17:06:29,469 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 17:06:29,469 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 17:06:29,587 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:06:30,514 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:06:30,514 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 17:06:30,518 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 17:06:31,522 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 17:06:31,525 INFO spawned: 'virtualgl' with pid 250
2024-12-25 17:06:31,526 INFO reaped unknown pid 154
2024-12-25 17:06:31,526 INFO reaped unknown pid 161
2024-12-25 17:06:31,526 INFO reaped unknown pid 166
2024-12-25 17:06:31,526 INFO reaped unknown pid 174
2024-12-25 17:06:31,568 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 17:06:31,647 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 17:06:32,651 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 17:06:32,694 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 17:06:33,420 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:06:33,459 views 31 140235855441920 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 17:06:27 +0000 UTC","ID":"4b0d3026fa7c","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-a69e5db2","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"6 seconds ago","Size":"429kB (virtual 14GB)","State":"running","Status":"Up 6 seconds"}
INFO 2024-12-25 17:06:33,459 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:45,943 views 32 140235855441920 Stopping container: openuav-a69e5db2
INFO 2024-12-25 17:06:45,943 views 32 140235855441920 Executing command: docker stop openuav-a69e5db2
INFO 2024-12-25 17:06:48,211 views 32 140235855441920 Command output - stdout: openuav-a69e5db2
INFO 2024-12-25 17:06:48,212 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:48,212 views 32 140235855441920 Executing command: docker rm openuav-a69e5db2
INFO 2024-12-25 17:06:48,254 views 32 140235855441920 Command output - stdout: openuav-a69e5db2
INFO 2024-12-25 17:06:48,255 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:48,263 views 32 140235855441920 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 17:06:48,267 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:48,267 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 17:06:48,281 views 32 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:06:48,312 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:06:48,313 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 17:10:45,454 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:10:45,489 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:10:45,489 views 31 140235855441920 Command return code: 0
INFO 2024-12-25 17:14:24,687 views 33 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:14:24,722 views 33 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:14:24,723 views 33 140235855441920 Command return code: 0
INFO 2024-12-25 17:14:25,841 views 33 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:14:25,876 views 33 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:14:25,876 views 33 140235855441920 Command return code: 0
INFO 2024-12-25 17:16:22,619 views 31 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 17:16:22,655 views 31 140235855441920 Command output - stdout: 
INFO 2024-12-25 17:16:22,655 views 31 140235855441920 Command return code: 0
ERROR 2024-12-25 17:55:38,939 exception 33 140235855441920 Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 17:55:38,992 log 33 140235855441920 Bad Request: /443
ERROR 2024-12-25 17:56:11,899 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 17:56:11,949 log 31 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 18:26:39,242 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 18:26:39,290 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 18:26:39,611 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 18:26:39,655 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-25 18:26:39,975 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 18:26:40,022 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 18:26:40,348 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 18:26:40,393 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-25 18:54:16,999 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 18:54:17,048 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 19:04:54,660 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 19:04:54,708 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 19:04:56,543 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 19:04:56,585 log 32 140235855441920 Bad Request: /
ERROR 2024-12-25 19:09:20,808 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 19:09:20,857 log 31 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 19:37:36,905 exception 33 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 19:37:36,954 log 33 140235855441920 Bad Request: /443
ERROR 2024-12-25 19:55:20,386 exception 31 140235855441920 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 19:55:20,433 log 31 140235855441920 Bad Request: /443
WARNING 2024-12-25 20:58:37,034 log 32 140235855441920 Not Found: /None
WARNING 2024-12-25 20:58:37,083 log 32 140235855441920 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-25 20:58:38,635 log 31 140235855441920 Not Found: /favicon.ico
INFO 2024-12-25 20:58:48,942 views 32 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 20:58:48,979 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:58:48,979 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:07,340 views 32 140235855441920 Received request to launch OpenUAV
INFO 2024-12-25 20:59:07,351 views 32 140235855441920 Launching container with name: openuav-462bffd5
INFO 2024-12-25 20:59:07,351 views 32 140235855441920 Checking if container already exists...
INFO 2024-12-25 20:59:07,351 views 32 140235855441920 Executing command: docker ps -a --filter name=openuav-462bffd5 --format '{{.Names}}'
INFO 2024-12-25 20:59:07,385 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:59:07,385 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:07,385 views 32 140235855441920 Cleaning up stale files...
INFO 2024-12-25 20:59:07,385 views 32 140235855441920 Executing command: rm -f /tmp/.X11-unix/X1
INFO 2024-12-25 20:59:07,390 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:59:07,390 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:07,390 views 32 140235855441920 Executing command: rm -f /tmp/.X1*
INFO 2024-12-25 20:59:07,394 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:59:07,394 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:07,394 views 32 140235855441920 Executing command: pkill -f Xvnc || true
INFO 2024-12-25 20:59:07,400 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:59:07,400 views 32 140235855441920 Command return code: -15
INFO 2024-12-25 20:59:07,401 views 32 140235855441920 Executing command: pkill -f vncserver || true
INFO 2024-12-25 20:59:07,406 views 32 140235855441920 Command output - stdout: 
INFO 2024-12-25 20:59:07,407 views 32 140235855441920 Command return code: -15
INFO 2024-12-25 20:59:07,407 views 32 140235855441920 Creating new container...
INFO 2024-12-25 20:59:07,407 views 32 140235855441920 Executing command: docker run -d --name openuav-462bffd5 --privileged --gpus all -p 6080:6080 -p 5901:5901 -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute -e VNC_PASSWORD=liftoff -v /tmp/.X11-unix:/tmp/.X11-unix:rw --runtime=nvidia openuav:px4-sitl /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
INFO 2024-12-25 20:59:08,433 views 32 140235855441920 Command output - stdout: 6eb2c1cc95ffa3081490c65b101c12a4d6a997c194b03b97a615a07468ef2a8d
INFO 2024-12-25 20:59:08,433 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:08,433 views 32 140235855441920 Container started successfully
INFO 2024-12-25 20:59:13,439 views 32 140235855441920 Executing command: docker inspect --format='{{.Id}}' openuav-462bffd5
INFO 2024-12-25 20:59:13,478 views 32 140235855441920 Command output - stdout: 6eb2c1cc95ffa3081490c65b101c12a4d6a997c194b03b97a615a07468ef2a8d
INFO 2024-12-25 20:59:13,478 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:13,487 views 32 140235855441920 Executing command: docker inspect openuav-462bffd5 --format '{{.State.Status}} {{.State.Running}}'
INFO 2024-12-25 20:59:13,523 views 32 140235855441920 Command output - stdout: running true
INFO 2024-12-25 20:59:13,523 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:13,523 views 32 140235855441920 Container state: running true
INFO 2024-12-25 20:59:13,523 views 32 140235855441920 Executing command: docker exec openuav-462bffd5 ps aux | grep Xvnc
INFO 2024-12-25 20:59:13,617 views 32 140235855441920 Command output - stdout: root          50  3.7  0.0 167056 64208 ?        S    20:59   0:00 /opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: 6eb2c1cc95ff:1 () -auth /root/.Xauthority -geometry 1920x1080 -depth 24 -rfbauth /root/.vnc/passwd -x509cert /root/.vnc/x509_cert.pem -x509key /root/.vnc/x509_private.pem -rfbport 5901 -fp /usr/share/fonts/X11/misc -deferupdate 1 -dridir /usr/lib/x86_64-linux-gnu/dri -registrydir /usr/lib/xorg
INFO 2024-12-25 20:59:13,617 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:13,617 views 32 140235855441920 Executing command: docker logs openuav-462bffd5 --tail 20
INFO 2024-12-25 20:59:13,654 views 32 140235855441920 Command output - stdout: 2024-12-25 20:59:09,729 INFO spawned: 'cleanup' with pid 20
2024-12-25 20:59:09,732 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 20:59:09,735 INFO spawned: 'novnc' with pid 22
2024-12-25 20:59:09,738 INFO spawned: 'virtualgl' with pid 23
2024-12-25 20:59:09,745 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 20:59:09,745 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 20:59:09,861 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 20:59:10,787 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 20:59:10,787 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 20:59:10,792 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 20:59:11,796 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 20:59:11,798 INFO spawned: 'virtualgl' with pid 250
2024-12-25 20:59:11,799 INFO reaped unknown pid 154
2024-12-25 20:59:11,799 INFO reaped unknown pid 161
2024-12-25 20:59:11,799 INFO reaped unknown pid 166
2024-12-25 20:59:11,799 INFO reaped unknown pid 172
2024-12-25 20:59:11,838 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 20:59:11,913 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 20:59:12,917 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 20:59:12,960 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 20:59:13,654 views 32 140235855441920 Command return code: 0
INFO 2024-12-25 20:59:13,654 views 32 140235855441920 Container recent logs: 2024-12-25 20:59:09,729 INFO spawned: 'cleanup' with pid 20
2024-12-25 20:59:09,732 INFO spawned: 'turbo_vnc' with pid 21
2024-12-25 20:59:09,735 INFO spawned: 'novnc' with pid 22
2024-12-25 20:59:09,738 INFO spawned: 'virtualgl' with pid 23
2024-12-25 20:59:09,745 INFO success: cleanup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-12-25 20:59:09,745 INFO exited: cleanup (exit status 1; not expected)
2024-12-25 20:59:09,861 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 20:59:10,787 INFO success: turbo_vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 20:59:10,787 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-25 20:59:10,792 INFO exited: turbo_vnc (exit status 0; expected)
2024-12-25 20:59:11,796 INFO spawned: 'turbo_vnc' with pid 249
2024-12-25 20:59:11,798 INFO spawned: 'virtualgl' with pid 250
2024-12-25 20:59:11,799 INFO reaped unknown pid 154
2024-12-25 20:59:11,799 INFO reaped unknown pid 161
2024-12-25 20:59:11,799 INFO reaped unknown pid 166
2024-12-25 20:59:11,799 INFO reaped unknown pid 172
2024-12-25 20:59:11,838 INFO exited: turbo_vnc (exit status 98; not expected)
2024-12-25 20:59:11,913 INFO exited: virtualgl (exit status 0; not expected)
2024-12-25 20:59:12,917 INFO spawned: 'turbo_vnc' with pid 319
2024-12-25 20:59:12,960 INFO exited: turbo_vnc (exit status 98; not expected)
INFO 2024-12-25 20:59:13,809 views 32 140235855441920 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-25 20:59:13,849 views 32 140235855441920 Command output - stdout: {"Command":"\"/usr/bin/supervisor…\"","CreatedAt":"2024-12-25 20:59:07 +0000 UTC","ID":"6eb2c1cc95ff","Image":"openuav:px4-sitl","Labels":"maintainer=NVIDIA CORPORATION \u003ccudatools@nvidia.com\u003e","LocalVolumes":"0","Mounts":"/tmp/.X11-unix","Names":"openuav-462bffd5","Networks":"bridge","Ports":"0.0.0.0:5901-\u003e5901/tcp, :::5901-\u003e5901/tcp, 0.0.0.0:6080-\u003e6080/tcp, :::6080-\u003e6080/tcp","RunningFor":"6 seconds ago","Size":"429kB (virtual 14GB)","State":"running","Status":"Up 6 seconds"}
INFO 2024-12-25 20:59:13,849 views 32 140235855441920 Command return code: 0
ERROR 2024-12-25 21:12:26,399 exception 31 140235855441920 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 21:12:26,446 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-25 21:25:19,764 exception 31 140235855441920 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 21:25:19,813 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 22:05:02,137 exception 32 140235855441920 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:05:02,182 log 32 140235855441920 Bad Request: /
ERROR 2024-12-25 22:05:03,056 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:05:03,098 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-25 22:05:03,425 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:05:03,469 log 31 140235855441920 Bad Request: /
ERROR 2024-12-25 22:05:03,793 exception 31 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:05:03,835 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-25 22:10:31,885 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:10:31,928 log 33 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-25 22:33:02,180 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 22:33:02,227 log 33 140235855441920 Bad Request: /
WARNING 2024-12-25 22:33:02,603 log 33 140235855441920 Not Found: /logon.htm
ERROR 2024-12-25 23:02:49,962 exception 32 140235855441920 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-25 23:02:50,010 log 32 140235855441920 Bad Request: /goform/set_LimitClient_cfg
ERROR 2024-12-25 23:19:25,319 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 23:19:25,369 log 32 140235855441920 Bad Request: /
ERROR 2024-12-25 23:50:50,409 exception 33 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-25 23:50:50,453 log 33 140235855441920 Bad Request: /443
ERROR 2024-12-25 23:55:30,711 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-25 23:55:30,760 log 31 140235855441920 Bad Request: /
ERROR 2024-12-26 00:18:45,411 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:18:45,458 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 00:21:17,013 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:21:17,061 log 32 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-26 00:54:07,207 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:54:07,254 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 00:55:12,842 exception 32 140235855441920 Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:55:12,889 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 00:55:36,135 exception 32 140235855441920 Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:55:36,183 log 32 140235855441920 Bad Request: /443
ERROR 2024-12-26 00:56:03,607 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:56:03,654 log 33 140235855441920 Bad Request: /geoserver/web/
ERROR 2024-12-26 00:58:45,760 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 00:58:45,807 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 01:07:01,291 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 01:07:01,343 log 31 140235855441920 Bad Request: /
ERROR 2024-12-26 01:51:36,020 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 01:51:36,068 log 31 140235855441920 Bad Request: /
ERROR 2024-12-26 02:01:03,596 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 02:01:03,643 log 33 140235855441920 Bad Request: /
WARNING 2024-12-26 02:01:04,007 log 33 140235855441920 Not Found: /logon.htm
ERROR 2024-12-26 02:14:03,272 exception 33 140235855441920 Invalid HTTP_HOST header: '0.0.0.0'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2024-12-26 02:14:03,320 log 33 140235855441920 Bad Request: /
WARNING 2024-12-26 02:24:15,808 log 32 140235855441920 Not Found: /favicon.ico
ERROR 2024-12-26 02:29:05,717 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 02:29:05,763 log 33 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-26 02:36:22,698 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 02:36:22,741 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 03:30:45,137 exception 31 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 03:30:45,184 log 31 140235855441920 Bad Request: /
ERROR 2024-12-26 03:31:38,800 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 03:31:38,848 log 32 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-26 03:45:53,126 exception 33 140235855441920 Invalid HTTP_HOST header: 'example.com:443'. You may need to add 'example.com' to ALLOWED_HOSTS.
WARNING 2024-12-26 03:45:53,172 log 33 140235855441920 Bad Request: /443
ERROR 2024-12-26 03:47:03,961 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 03:47:04,008 log 33 140235855441920 Bad Request: /actuator/gateway/routes
ERROR 2024-12-26 04:01:45,865 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:01:45,912 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 04:01:50,926 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:01:50,973 log 32 140235855441920 Bad Request: /
ERROR 2024-12-26 04:14:37,467 exception 33 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:14:37,513 log 33 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
ERROR 2024-12-26 04:26:36,361 exception 31 140235855441920 Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:26:36,418 log 31 140235855441920 Bad Request: /443
ERROR 2024-12-26 04:29:57,742 exception 32 140235855441920 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:29:57,788 log 32 140235855441920 Bad Request: /cgi-bin/luci/;stok=/locale
WARNING 2024-12-26 04:51:05,173 log 31 140235855441920 Not Found: /None
WARNING 2024-12-26 04:51:05,244 log 31 140235855441920 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 04:51:07,935 log 32 140235855441920 Not Found: /None
WARNING 2024-12-26 04:51:07,949 log 31 140235855441920 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 04:51:10,230 log 31 140235855441920 Not Found: /favicon.ico
WARNING 2024-12-26 04:54:20,609 log 33 140235855441920 Not Found: /None
WARNING 2024-12-26 04:54:20,654 log 33 140235855441920 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 04:54:22,827 log 32 140235855441920 Not Found: /favicon.ico
WARNING 2024-12-26 04:57:15,561 log 32 139933300924416 Not Found: /None
WARNING 2024-12-26 04:57:17,767 log 31 139933300924416 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 04:57:53,871 log 32 139933300924416 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 04:57:54,092 log 33 139933300924416 Not Found: /None
ERROR 2024-12-26 04:58:01,574 exception 33 139933300924416 Invalid HTTP_HOST header: 'xr.localhost'. You may need to add 'xr.localhost' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:58:01,626 log 33 139933300924416 Bad Request: /
ERROR 2024-12-26 04:58:01,809 exception 33 139933300924416 Invalid HTTP_HOST header: 'xr.localhost'. You may need to add 'xr.localhost' to ALLOWED_HOSTS.
WARNING 2024-12-26 04:58:01,856 log 33 139933300924416 Bad Request: /favicon.ico
WARNING 2024-12-26 05:01:41,086 log 33 139933300924416 Not Found: /None
WARNING 2024-12-26 05:01:41,303 log 31 139933300924416 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:03:23,690 log 32 140172504739840 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:03:24,860 log 33 140172504739840 Not Found: /None
WARNING 2024-12-26 05:05:44,807 log 32 140172504739840 Not Found: /None
WARNING 2024-12-26 05:05:46,016 log 31 140172504739840 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:06:24,420 log 33 140172504739840 Not Found: /None
WARNING 2024-12-26 05:06:24,429 log 31 140172504739840 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:23:32,114 log 31 140172504739840 Not Found: /None
WARNING 2024-12-26 05:23:32,481 log 31 140172504739840 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:23:39,340 log 31 140172504739840 Not Found: /None
WARNING 2024-12-26 05:23:39,637 log 31 140172504739840 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:23:42,419 log 31 140172504739840 Not Found: /favicon.ico
WARNING 2024-12-26 05:33:46,912 log 31 139879510306816 Not Found: /None
WARNING 2024-12-26 05:33:46,974 log 31 139879510306816 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:33:47,666 log 31 139879510306816 Not Found: /favicon.ico
ERROR 2024-12-26 05:35:34,366 exception 32 139879510306816 Invalid HTTP_HOST header: '68.109.135.117:x'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-12-26 05:35:34,423 log 32 139879510306816 Bad Request: /
ERROR 2024-12-26 05:37:18,530 exception 32 139879510306816 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 05:37:18,578 log 32 139879510306816 Bad Request: /.env
WARNING 2024-12-26 05:39:50,818 log 33 139879510306816 Not Found: /None
WARNING 2024-12-26 05:39:50,990 log 33 139879510306816 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:39:51,315 log 33 139879510306816 Not Found: /favicon.ico
INFO 2024-12-26 05:39:54,379 views 32 139879510306816 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-26 05:39:54,553 views 32 139879510306816 Command output - stdout: 
INFO 2024-12-26 05:39:54,553 views 32 139879510306816 Command return code: 0
INFO 2024-12-26 05:39:55,872 views 32 139879510306816 Received request to launch OpenUAV
INFO 2024-12-26 05:39:55,880 views 32 139879510306816 Found existing container: openuav-462bffd5
INFO 2024-12-26 05:39:55,893 views 32 139879510306816 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-26 05:39:55,926 views 32 139879510306816 Command output - stdout: 
INFO 2024-12-26 05:39:55,926 views 32 139879510306816 Command return code: 0
WARNING 2024-12-26 05:39:55,982 log 32 139879510306816 Not Found: /favicon.ico
WARNING 2024-12-26 05:42:22,893 log 32 139879510306816 Not Found: /None
WARNING 2024-12-26 05:42:22,955 log 32 139879510306816 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:42:23,983 log 32 139879510306816 Not Found: /favicon.ico
WARNING 2024-12-26 05:42:24,199 log 33 139879510306816 Not Found: /None
WARNING 2024-12-26 05:42:24,206 log 32 139879510306816 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:44:08,423 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:14,637 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:15,151 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:15,700 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:16,451 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:16,490 log 33 139879510306816 Not Found: /favicon.ico
WARNING 2024-12-26 05:44:17,089 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:18,834 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:29,603 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:30,150 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:33,336 log 33 139879510306816 Not Found: /None
WARNING 2024-12-26 05:44:33,344 log 31 139879510306816 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:44:33,466 log 31 139879510306816 Not Found: /favicon.ico
WARNING 2024-12-26 05:44:34,370 log 31 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:44:36,539 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:45:32,147 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:45:33,549 log 33 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:46:02,518 log 31 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:46:05,997 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:46:06,428 log 32 139879510306816 Not Found: /xr
WARNING 2024-12-26 05:46:31,377 log 33 140074856919040 Not Found: /xr
WARNING 2024-12-26 05:46:32,166 log 33 140074856919040 Not Found: /xr
ERROR 2024-12-26 05:47:01,056 exception 31 140074856919040 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 05:47:01,099 log 31 140074856919040 Bad Request: /
WARNING 2024-12-26 05:47:29,237 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 05:47:29,322 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:47:32,430 log 33 140074856919040 Not Found: /xr
WARNING 2024-12-26 05:47:57,144 log 33 140074856919040 Not Found: /xr
WARNING 2024-12-26 05:47:57,588 log 33 140074856919040 Not Found: /xr
WARNING 2024-12-26 05:51:01,942 log 31 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:51:03,077 log 32 140074856919040 Not Found: /None
ERROR 2024-12-26 05:51:15,234 exception 32 140074856919040 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 05:51:15,291 log 32 140074856919040 Bad Request: /
ERROR 2024-12-26 05:53:01,297 exception 33 140074856919040 Invalid HTTP_HOST header: '68.109.135.117:8080'. You may need to add '68.109.135.117' to ALLOWED_HOSTS.
WARNING 2024-12-26 05:53:01,347 log 33 140074856919040 Bad Request: /cgi-bin/luci/;stok=/locale
WARNING 2024-12-26 05:53:35,984 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 05:53:35,991 log 32 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:53:37,140 log 33 140074856919040 Not Found: /None
WARNING 2024-12-26 05:53:37,146 log 32 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:55:00,699 log 33 140074856919040 Not Found: /None
WARNING 2024-12-26 05:55:00,704 log 31 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:57:04,333 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 05:57:04,345 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 05:57:07,316 log 31 140074856919040 Not Found: /favicon.ico
WARNING 2024-12-26 06:05:46,617 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 06:05:46,624 log 32 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:05:46,898 log 32 140074856919040 Not Found: /None
WARNING 2024-12-26 06:05:46,901 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:05:47,117 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 06:05:47,117 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:18:28,197 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 06:18:28,206 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:18:28,641 log 31 140074856919040 Not Found: /None
WARNING 2024-12-26 06:18:28,647 log 33 140074856919040 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:21:54,610 log 33 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:21:55,859 log 32 140042657062912 Not Found: /None
WARNING 2024-12-26 06:22:06,092 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:22:07,347 log 31 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:26:41,738 log 31 140042657062912 Not Found: /None
WARNING 2024-12-26 06:26:41,753 log 33 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:26:42,845 log 32 140042657062912 Not Found: /None
WARNING 2024-12-26 06:26:42,848 log 33 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:26:45,342 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:26:45,606 log 33 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:28:47,586 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:28:47,596 log 32 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:28:48,816 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:28:48,823 log 32 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:28:50,222 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:28:50,228 log 31 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:28:53,448 log 33 140042657062912 Not Found: /favicon.ico
WARNING 2024-12-26 06:29:00,385 log 33 140042657062912 Not Found: /None
WARNING 2024-12-26 06:29:00,387 log 31 140042657062912 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:29:06,770 log 31 140042657062912 Not Found: /None
WARNING 2024-12-26 06:29:06,775 log 32 140042657062912 Not Found: /static/images/planetary_background.jpg
ERROR 2024-12-26 06:29:38,386 log 31 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
ERROR 2024-12-26 06:29:39,287 log 31 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
ERROR 2024-12-26 06:29:40,026 log 31 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
ERROR 2024-12-26 06:29:42,046 log 31 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
ERROR 2024-12-26 06:29:42,303 log 32 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
ERROR 2024-12-26 06:29:42,907 log 32 140606251057152 Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 560, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/dreams_laboratory/urls.py", line 62, in <module>
    path('xr/', include('deepgis_xr.urls')),
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'deepgis_xr'
INFO 2024-12-26 06:32:04,554 views 32 140606251057152 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-26 06:32:04,591 views 32 140606251057152 Command output - stdout: 
INFO 2024-12-26 06:32:04,591 views 32 140606251057152 Command return code: 0
INFO 2024-12-26 06:32:06,812 views 32 140606251057152 Received request to launch OpenUAV
INFO 2024-12-26 06:32:06,822 views 32 140606251057152 Found existing container: openuav-462bffd5
INFO 2024-12-26 06:32:06,831 views 32 140606251057152 Executing command: docker ps --format '{{json .}}' --filter name=openuav
INFO 2024-12-26 06:32:06,867 views 32 140606251057152 Command output - stdout: 
INFO 2024-12-26 06:32:06,868 views 32 140606251057152 Command return code: 0
WARNING 2024-12-26 06:32:21,301 log 32 140606251057152 Not Found: /dreamslab/None
WARNING 2024-12-26 06:32:21,582 log 32 140606251057152 Not Found: /static/images/planetary_background.jpg
WARNING 2024-12-26 06:34:15,906 log 31 140606251057152 Not Found: /favicon.ico
WARNING 2024-12-26 06:35:22,598 log 32 140606251057152 Not Found: /dreamslab/None
WARNING 2024-12-26 06:35:22,715 log 32 140606251057152 Not Found: /static/images/planetary_background.jpg
